# Active profile: develop
spring:
  profiles:
    active: develop

server:
  port: 8090

# Develop profile configuration
---
spring:
  config:
    activate:
      on-profile: develop
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update 
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ""   
    initialize: true
  h2:
    console:
      enabled: true  
      path: /h2-console  
  sql:
    init:
      mode: always
      platform: h2

stripe:
  simulator:
    charges-uri: https://sandbox.playtomic.io/v1/stripe-simulator/charges
    refunds-uri: https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds

# Test profile configuration
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: create 
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ""    
    initialize: false
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2  
      mode: never

stripe:
  simulator:
    charges-uri: http://localhost:9999
    refunds-uri: http://localhost:9999
